services:
 # FastAPI Backend Service
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    volumes:
      - ./blog/content:/app/blog/content  # Sync MD files
      - /var/run/docker.sock:/var/run/docker.sock  # Allows FastAPI to trigger docker commands
    networks:
      - app-network
  hugo:
    container_name: blog
    image: klakegg/hugo:ext-alpine
    volumes:
      - ./blog:/src
    command:  server --bind=0.0.0.0 --port=1313 --watch
    ports:
      - "1313:1313"
networks:
  app-network:
    driver: bridge
