version: "3.8"

services:
  #########################################
  # Application Services
  #########################################

  # FastAPI Backend Service (Converge Backend)
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"  # API listens on 8001; global Nginx will proxy to localhost:8001
    volumes:
      - ./app:/app
      - ./app/mcp-servers:/app/mcp-servers
    env_file:
      - ./app/.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=converge
      - VIRTUAL_HOST=converge-backend.sleebit.com
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=converge-backend.sleebit.com
      - LETSENCRYPT_EMAIL=thesleebit@gmail.com
    depends_on:
      - mongo
      - sequential
      - twitter
      - youtube
    networks:
      - proxy-network

  # Static Vue.js Service (Frontend for Converge Backend)
  static-vue:
    image: nginx:alpine
    container_name: static-vue
    ports:
      - "8080:80"  # Container serves static files on port 80; global Nginx will proxy from ai.sleebit.com to localhost:8080
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=ai.sleebit.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ai.sleebit.com
      - LETSENCRYPT_EMAIL=thesleebit@gmail.com
    networks:
      - proxy-network

  # Blog Service (Static Site via Hugo)
  blog:
    image: nginx:alpine
    container_name: blog
    ports:
      - "8081:80"  # Container serves static files on port 80; global Nginx will proxy from blog.sleebit.com to localhost:8081
    volumes:
      - ./blog/public:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=blog.sleebit.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blog.sleebit.com
      - LETSENCRYPT_EMAIL=thesleebit@gmail.com
    networks:
      - proxy-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy-network

  # MCP Server: Sequential Service
  sequential:
    image: node:18-alpine
    container_name: sequential-service
    working_dir: /app
    volumes:
      - ./app/mcp-servers/sequential:/app
    command: sh -c "yarn install && node index.js"
    ports:
      - "4003:4003"
    env_file:
      - ./app/mcp-servers/.env
    networks:
      - proxy-network

  # MCP Server: Twitter Service
  twitter:
    image: node:18-alpine
    container_name: twitter-service
    working_dir: /app
    volumes:
      - ./app/mcp-servers/twitter:/app
    command: sh -c "yarn install && node index.js"
    ports:
      - "4004:4004"
    env_file:
      - ./app/mcp-servers/.env
    networks:
      - proxy-network

  # MCP Server: YouTube Service
  youtube:
    image: node:22-slim
    container_name: youtube-service
    working_dir: /app
    volumes:
      - ./app/mcp-servers/youtube:/app
    command: sh -c "apt-get update && apt-get install -y ffmpeg curl python3 && yarn install && yarn build && node dist/index.js"
    ports:
      - "4005:4005"
    env_file:
      - ./app/mcp-servers/.env
    networks:
      - proxy-network

  #########################################
  # Certbot Service (One-shot certificate generation)
  #########################################
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Certificates will be stored here on the host
      - /var/www/certbot:/var/www/certbot    # Webroot for ACME challenge; ensure your global Nginx serves this directory!
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      -d converge-backend.sleebit.com -d ai.sleebit.com -d blog.sleebit.com
      --email thesleebit@gmail.com --agree-tos --non-interactive

  #########################################
  # Config-Updater Services (One-shot jobs)
  #########################################

  # Update config for converge-backend.sleebit.com (API)
  update-converge-backend:
    image: alpine:latest
    container_name: update-converge-backend
    volumes:
      - /etc/nginx/conf.d:/nginx-conf
      - ./converge-backend.sleebit.com.conf:/project/converge-backend.sleebit.com.conf:ro
    entrypoint: sh -c "cp /project/converge-backend.sleebit.com.conf /nginx-conf/ && echo 'converge-backend config updated. Reload Nginx on host.'"
    restart: "no"
    networks:
      - proxy-network

  # Update config for ai.sleebit.com (Static Vue.js)
  update-ai:
    image: alpine:latest
    container_name: update-ai
    volumes:
      - /etc/nginx/conf.d:/nginx-conf
      - ./ai.sleebit.com.conf:/project/ai.sleebit.com.conf:ro
    entrypoint: sh -c "cp /project/ai.sleebit.com.conf /nginx-conf/ && echo 'ai config updated. Reload Nginx on host.'"
    restart: "no"
    networks:
      - proxy-network

  # Update config for blog.sleebit.com (Blog)
  update-blog:
    image: alpine:latest
    container_name: update-blog
    volumes:
      - /etc/nginx/conf.d:/nginx-conf
      - ./blog.sleebit.com.conf:/project/blog.sleebit.com.conf:ro
    entrypoint: sh -c "cp /project/blog.sleebit.com.conf /nginx-conf/ && echo 'blog config updated. Reload Nginx on host.'"
    restart: "no"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  mongo-data:
