services:
  # FastAPI Backend Service
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    volumes:
      - ./blog/content:/app/blog/content  # Sync MD files
      - /var/run/docker.sock:/var/run/docker.sock  # Allows FastAPI to trigger docker commands
    networks:
      - converge-network
    depends_on:
      mongodb:
        condition: service_healthy  # Wait until MongoDB is healthy before starting
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB Service
  mongodb:
    container_name: converge_mongodb
    image: mongo:6.0
    volumes:
      - /home/ubuntu/converge-mongo-data:/data/db  # Persist MongoDB data with full path
    networks:
      - converge-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb:27017/test
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  hugo:
    build:
      context: ./blog
      dockerfile: Dockerfile
    container_name: hugo_builder
    volumes:
      - /var/www/blog:/src/public
      - ./blog:/src  # so changes in the repo reflect inside the container
    restart: always

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    volumes:
      - /var/www/converge-frontend:/target
    command: ["sh", "-c", "cp -R /build_dist/* /target/ && tail -f /dev/null"]

# Docker Network
networks:
  converge-network:
    driver: bridge
