services:
  # FastAPI Backend Service
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    volumes:
      - ./blog/content:/app/blog/content  # Sync MD files
      - /var/run/docker.sock:/var/run/docker.sock  # Allows FastAPI to trigger docker commands
    networks:
      - converge-network
    depends_on:
      mongodb:
        condition: service_healthy  # Wait until MongoDB is healthy before starting

  # MongoDB Service
  mongodb:
    container_name: converge_mongodb
    image: mongo:6.0
    volumes:
      - /home/ubuntu/converge-mongo-data:/data/db  # Persist MongoDB data with full path
    networks:
      - converge-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb:27017/test
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  # Hugo Blog Service
  # hugo:
  #   container_name: blog
  #   image: klakegg/hugo:ext-alpine
  #   volumes:
  #     - ./blog:/src
  #   command: server --bind=0.0.0.0 --port=1313 --watch --renderToDisk
  #   ports:
  #     - "1313:1313"

  hugo:
    build:
      context: ./blog
      dockerfile: Dockerfile.hugo
    container_name: hugo_builder
    volumes:
      - /var/www/blog:/src/public
      - ./blog:/src  # so changes in the repo reflect inside the container
    restart: always
  
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile.vue
    container_name: vue_app
    volumes:
      - /var/www/converge-frontend:/src/dist
    command: "sh -c 'npm run build && cp -R dist/ /mounted-frontend'"
    # We'll mount /mounted-frontend to host below



# Docker Network
networks:
  converge-network:
    driver: bridge