services:
  # core:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #     - redis

  medium:
    build:
      context: ./medium
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - .env

  sequential:
    build:
      context: ./sequential
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    env_file:
      - .env

  twitter:
    build:
      context: ./twitter
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    env_file:
      - .env

  youtube:
    build:
      context: ./youtube
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6380:6379"

volumes:
  mongo-data:
