[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/thesleebit"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/codeit13/converge"
  weight = 40

[[footer]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 20